//! Emit `shopify.d.ts` for UI extensions (string-level parity with upstream).

use crate::error::AppError;
use crate::models::extensions::extension_instance::ExtensionInstance;
use std::fs;
use std::path::Path;

const HEADER: &str = r#"// Generated by Shopify CLI. Do not edit this file.
/// <reference types="@shopify/ui-extensions" />
"#;

/// Build TypeScript ambient declarations for a UI extension's targeting.
pub fn generate_ui_extension_types(ext: &ExtensionInstance) -> String {
    let mut targets = Vec::new();
    if let Some(Value::Array(arr)) = ext.configuration.get("targeting") {
        for item in arr {
            if let Some(t) = item.get("target").and_then(|v| v.as_str()) {
                targets.push(t.to_string());
            }
        }
    }
    let mut out = String::from(HEADER);
    if targets.is_empty() {
        out.push_str("export {};\n");
        return out;
    }
    out.push_str("declare module './src/index' {\n");
    for target in &targets {
        out.push_str(&format!(
            "  const shopify: import('@shopify/ui-extensions/{target}').Api;\n"
        ));
    }
    out.push_str("}\nexport {};\n");
    out
}

/// Write `shopify.d.ts` next to the extension source when the spec is a UI extension.
pub fn write_ui_extension_types(
    ext: &ExtensionInstance,
    directory: &Path,
) -> Result<bool, AppError> {
    if !ext.is_ui_extension() {
        return Ok(false);
    }
    let content = generate_ui_extension_types(ext);
    fs::write(directory.join("shopify.d.ts"), content)?;
    Ok(true)
}

use serde_json::Value;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::extensions::specification::create_extension_specification;
    use std::collections::HashMap;
    use std::path::PathBuf;
    use tempfile::tempdir;

    #[test]
    fn emits_targets() {
        let spec = create_extension_specification("ui_extension").unwrap();
        let mut cfg = HashMap::new();
        cfg.insert(
            "targeting".into(),
            serde_json::json!([{ "target": "purchase.checkout.block.render" }]),
        );
        let ext = ExtensionInstance::new(
            "ui",
            PathBuf::from("extensions/ui"),
            PathBuf::from("extensions/ui/shopify.extension.toml"),
            cfg,
            spec,
        );
        let dts = generate_ui_extension_types(&ext);
        assert!(dts.contains("purchase.checkout.block.render"));
        assert!(dts.contains("@shopify/ui-extensions"));
    }

    #[test]
    fn writes_file_for_ui() {
        let dir = tempdir().unwrap();
        let spec = create_extension_specification("ui_extension").unwrap();
        let ext = ExtensionInstance::new(
            "ui",
            dir.path().to_path_buf(),
            dir.path().join("shopify.extension.toml"),
            HashMap::new(),
            spec,
        );
        assert!(write_ui_extension_types(&ext, dir.path()).unwrap());
        assert!(dir.path().join("shopify.d.ts").exists());
    }

    #[test]
    fn skips_theme() {
        let dir = tempdir().unwrap();
        let spec = create_extension_specification("theme").unwrap();
        let ext = ExtensionInstance::new(
            "t",
            dir.path().to_path_buf(),
            dir.path().join("shopify.extension.toml"),
            HashMap::new(),
            spec,
        );
        assert!(!write_ui_extension_types(&ext, dir.path()).unwrap());
        assert!(!dir.path().join("shopify.d.ts").exists());
    }
}
