use crate::types::*;
use std::collections::HashSet;

/// Options for code generation.
#[derive(Default)]
pub struct GenOptions {
    pub module_name: String,
}

struct GenState {
    seen: HashSet<String>,
}

/// Generate Rust code for shared GraphQL input types and enums.
pub fn generate_shared_types(shared_types: &[SharedType]) -> String {
    let mut code = String::new();
    let mut state = GenState {
        seen: HashSet::new(),
    };

    push_header(&mut code);
    code.push_str("use serde::{Deserialize, Serialize};\n\n");
    emit_one_or_many(&mut code);

    let shared_op = GraphqlOperation {
        operation_type: GraphqlOperationType::Query,
        operation_name: String::new(),
        raw_query: String::new(),
        variables: Vec::new(),
    };
    for st in shared_types {
        generate_shared_type(&mut code, st, &mut state, &shared_op);
    }

    code
}

/// Generate Rust code for a single GraphQL operation.
pub fn generate_rust(output: &RustOutput, _opts: &GenOptions) -> String {
    let mut code = String::new();
    let mut state = GenState {
        seen: HashSet::new(),
    };

    push_header(&mut code);
    code.push_str("use serde::{Deserialize, Serialize};\n\n");
    code.push_str("use super::types::*;\n\n");

    let query_literal = raw_string_literal(&output.operation.raw_query);
    code.push_str(&format!(
        "pub const {}: &str = {};\n\n",
        output.query_constant_name, query_literal
    ));

    if let Some(TsType::Object(fields)) = output.variables_struct.as_ref().and_then(unwrap_exact) {
        if !fields.is_empty() {
            emit_nested_fields(
                &mut code,
                fields,
                &output.operation,
                &[],
                DeriveMode::Serialize,
                &mut state,
            );
            emit_struct(
                &mut code,
                &format!("{}Variables", pascal_case(&output.operation.operation_name)),
                fields,
                &output.operation,
                &[],
                DeriveMode::Serialize,
                &mut state,
            );
        }
    }

    if let TsType::Object(fields) = &output.response_struct {
        emit_nested_fields(
            &mut code,
            fields,
            &output.operation,
            &[],
            DeriveMode::Deserialize,
            &mut state,
        );
        emit_struct(
            &mut code,
            &format!("{}Response", pascal_case(&output.operation.operation_name)),
            fields,
            &output.operation,
            &[],
            DeriveMode::Deserialize,
            &mut state,
        );
    }

    code
}

fn push_header(code: &mut String) {
    code.push_str("// Auto-generated by graphql-codegen. Do not edit.\n");
    code.push_str("#![allow(clippy::all)]\n");
    code.push_str("#![allow(unused_imports)]\n");
    code.push_str("#![allow(dead_code)]\n\n");
}

fn emit_one_or_many(code: &mut String) {
    code.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    code.push_str("#[serde(untagged)]\n");
    code.push_str("pub enum OneOrMany<T> {\n");
    code.push_str("  One(T),\n");
    code.push_str("  Many(Vec<T>),\n");
    code.push_str("}\n\n");
}

#[derive(Clone, Copy)]
enum DeriveMode {
    Serialize,
    Deserialize,
}

fn unwrap_exact(typ: &TsType) -> Option<&TsType> {
    match typ {
        TsType::Wrapped(w) if matches!(w.wrapper.as_str(), "Exact" | "Types.Exact") => {
            Some(&w.inner)
        }
        _ => Some(typ),
    }
}

fn generate_shared_type(
    code: &mut String,
    st: &SharedType,
    state: &mut GenState,
    op: &GraphqlOperation,
) {
    match &st.kind {
        SharedTypeKind::Enum { variants } => {
            let name = pascal_case(&st.name);
            if !state.seen.insert(name.clone()) {
                return;
            }
            code.push_str(&format!(
                "#[derive(Debug, Clone, Serialize, Deserialize)]\npub enum {} {{\n",
                name
            ));
            for variant in variants {
                let rust_variant = enum_variant_name(variant);
                code.push_str(&format!(
                    "  #[serde(rename = \"{}\")]\n  {},\n",
                    variant, rust_variant
                ));
            }
            code.push_str("}\n\n");
        }
        SharedTypeKind::InputStruct { fields } => {
            let name = pascal_case(&st.name);
            emit_nested_fields(
                code,
                fields,
                op,
                &[st.name.as_str()],
                DeriveMode::Serialize,
                state,
            );
            emit_struct(
                code,
                &name,
                fields,
                op,
                &[st.name.as_str()],
                DeriveMode::Serialize,
                state,
            );
        }
    }
}

fn emit_nested_fields(
    code: &mut String,
    fields: &[TsField],
    op: &GraphqlOperation,
    parent_path: &[&str],
    mode: DeriveMode,
    state: &mut GenState,
) {
    for field in fields {
        let path = path_with(parent_path, &field.name);
        emit_nested_type(code, &field.field_type, op, &path, mode, state);
    }
}

fn emit_nested_type(
    code: &mut String,
    typ: &TsType,
    op: &GraphqlOperation,
    path: &[&str],
    mode: DeriveMode,
    state: &mut GenState,
) {
    match strip_nullable_wrapper(typ) {
        TsType::Object(fields) => {
            emit_nested_fields(code, &fields, op, path, mode, state);
            let name = type_name_for_path(op, path);
            emit_struct(code, &name, &fields, op, path, mode, state);
        }
        TsType::Array(elem) => emit_nested_type(code, &elem, op, path, mode, state),
        TsType::DiscriminatedUnion { variants, .. } => {
            for variant in &variants {
                let variant_path = path_with(path, &variant.type_name);
                emit_nested_fields(code, &variant.fields, op, &variant_path, mode, state);
                let variant_struct = type_name_for_path(op, &variant_path);
                emit_struct(
                    code,
                    &variant_struct,
                    &variant.fields,
                    op,
                    &variant_path,
                    mode,
                    state,
                );
            }
            emit_union_enum(code, op, path, &variants, state);
        }
        TsType::Union(alts) => {
            for alt in &alts {
                emit_nested_type(code, alt, op, path, mode, state);
            }
        }
        _ => {}
    }
}

fn emit_struct(
    code: &mut String,
    name: &str,
    fields: &[TsField],
    op: &GraphqlOperation,
    path: &[&str],
    mode: DeriveMode,
    state: &mut GenState,
) {
    if !state.seen.insert(name.to_string()) {
        return;
    }

    match mode {
        DeriveMode::Serialize => {
            code.push_str("#[derive(Debug, Clone, Serialize)]\n");
        }
        DeriveMode::Deserialize => {
            code.push_str("#[derive(Debug, Clone, Deserialize)]\n");
        }
    }
    code.push_str("#[serde(rename_all = \"camelCase\")]\n");
    code.push_str(&format!("pub struct {} {{\n", name));
    for field in fields {
        generate_field_code(code, field, mode, op, path);
    }
    code.push_str("}\n\n");
}

fn emit_union_enum(
    code: &mut String,
    op: &GraphqlOperation,
    path: &[&str],
    variants: &[TsObjectVariant],
    state: &mut GenState,
) {
    let enum_name = type_name_for_path(op, path);
    if !state.seen.insert(enum_name.clone()) {
        return;
    }

    code.push_str("#[derive(Debug, Clone, Deserialize)]\n");
    code.push_str("#[serde(tag = \"__typename\")]\n");
    code.push_str(&format!("pub enum {} {{\n", enum_name));
    for variant in variants {
        let variant_path = path_with(path, &variant.type_name);
        let variant_struct = type_name_for_path(op, &variant_path);
        code.push_str(&format!(
            "  #[serde(rename = \"{}\")]\n  {}({}),\n",
            variant.type_name,
            enum_variant_name(&variant.type_name),
            variant_struct
        ));
    }
    code.push_str("}\n\n");
}

fn generate_field_code(
    code: &mut String,
    field: &TsField,
    mode: DeriveMode,
    op: &GraphqlOperation,
    parent_path: &[&str],
) {
    let field_path = path_with(parent_path, &field.name);
    let mut rust_type = ts_type_to_rust(&field.field_type, op, &field_path);
    if field.optional && !is_nullable_like(&field.field_type) {
        rust_type = format!("Option<{rust_type}>");
    }

    let field_ident = rust_field_ident(&field.name);
    if matches!(mode, DeriveMode::Serialize) && field.optional {
        code.push_str("  #[serde(skip_serializing_if = \"Option::is_none\")]\n");
    }
    if field_ident.needs_rename {
        code.push_str(&format!("  #[serde(rename = \"{}\")]\n", field.name));
    }
    code.push_str(&format!("  pub {}: {},\n", field_ident.name, rust_type));
}

fn ts_type_to_rust(typ: &TsType, op: &GraphqlOperation, path: &[&str]) -> String {
    match typ {
        TsType::Primitive(p) => p.to_string(),
        TsType::Array(elem) => format!("Vec<{}>", ts_type_to_rust(elem, op, path)),
        TsType::Nullable(inner) => format!("Option<{}>", ts_type_to_rust(inner, op, path)),
        TsType::Union(alts) => union_to_rust(alts, op, path),
        TsType::StringUnion(_) => "String".to_string(),
        TsType::Reference(TsReference::Named(parts)) => resolve_reference(parts),
        TsType::Reference(TsReference::Indexed { base, keys }) => resolve_indexed(base, keys),
        TsType::Wrapped(w) => match w.wrapper.as_str() {
            "Maybe" | "InputMaybe" | "Types.Maybe" | "Types.InputMaybe" => {
                format!("Option<{}>", ts_type_to_rust(&w.inner, op, path))
            }
            "Exact" | "Types.Exact" | "Pick" | "Types.Pick" | "Partial" | "Types.Partial" => {
                ts_type_to_rust(&w.inner, op, path)
            }
            _ => ts_type_to_rust(&w.inner, op, path),
        },
        TsType::Object(_) | TsType::DiscriminatedUnion { .. } => type_name_for_path(op, path),
    }
}

fn union_to_rust(alts: &[TsType], op: &GraphqlOperation, path: &[&str]) -> String {
    let non_null: Vec<&TsType> = alts
        .iter()
        .filter(|alt| !matches!(alt, TsType::Primitive(TsPrimitive::Any)))
        .collect();

    if non_null.len() == 2 {
        if let Some(inner) = one_or_many_inner(non_null[0], non_null[1]) {
            return format!("OneOrMany<{}>", ts_type_to_rust(inner, op, path));
        }
    }

    if non_null
        .iter()
        .any(|alt| matches!(alt, TsType::Reference(TsReference::Named(parts)) if parts.last().is_some_and(|p| p == "JsonMapType")))
    {
        return "serde_json::Value".to_string();
    }

    "serde_json::Value".to_string()
}

fn one_or_many_inner<'a>(left: &'a TsType, right: &'a TsType) -> Option<&'a TsType> {
    match (left, right) {
        (TsType::Array(elem), other) if same_type(elem, other) => Some(other),
        (other, TsType::Array(elem)) if same_type(elem, other) => Some(other),
        _ => None,
    }
}

fn same_type(left: &TsType, right: &TsType) -> bool {
    match (left, right) {
        (TsType::Primitive(a), TsType::Primitive(b)) => {
            std::mem::discriminant(a) == std::mem::discriminant(b)
        }
        (TsType::Reference(TsReference::Named(a)), TsType::Reference(TsReference::Named(b))) => {
            a == b
        }
        (
            TsType::Reference(TsReference::Indexed {
                base: a_base,
                keys: a_keys,
            }),
            TsType::Reference(TsReference::Indexed {
                base: b_base,
                keys: b_keys,
            }),
        ) => a_base == b_base && a_keys == b_keys,
        _ => false,
    }
}

fn strip_nullable_wrapper(typ: &TsType) -> TsType {
    match typ {
        TsType::Nullable(inner) => strip_nullable_wrapper(inner),
        TsType::Wrapped(w)
            if matches!(
                w.wrapper.as_str(),
                "Maybe" | "InputMaybe" | "Types.Maybe" | "Types.InputMaybe"
            ) =>
        {
            strip_nullable_wrapper(&w.inner)
        }
        _ => typ.clone(),
    }
}

fn is_nullable_like(typ: &TsType) -> bool {
    matches!(typ, TsType::Nullable(_))
        || matches!(
            typ,
            TsType::Wrapped(w)
                if matches!(
                    w.wrapper.as_str(),
                    "Maybe" | "InputMaybe" | "Types.Maybe" | "Types.InputMaybe"
                )
        )
}

fn resolve_reference(parts: &[String]) -> String {
    if parts.last().is_some_and(|p| p == "JsonMapType") {
        return "serde_json::Value".to_string();
    }
    if parts.len() >= 2 && parts[0] == "Types" {
        parts[1..].iter().map(|p| pascal_case(p)).collect()
    } else {
        parts.iter().map(|p| pascal_case(p)).collect()
    }
}

fn resolve_indexed(base: &[String], keys: &[String]) -> String {
    let is_scalars = (base.len() >= 2 && base[0] == "Types" && base[1] == "Scalars")
        || (base.len() == 1 && base[0] == "Scalars");
    if is_scalars && keys.len() >= 2 {
        match keys[0].as_str() {
            "String" | "ID" | "URL" | "GlobalID" | "PropertyId" | "PropertyPublicID" => {
                "String".to_string()
            }
            "Boolean" => "bool".to_string(),
            "Int" => "i64".to_string(),
            "Float" => "f64".to_string(),
            "JSON" => "serde_json::Value".to_string(),
            _ => "serde_json::Value".to_string(),
        }
    } else {
        base.iter().map(|p| pascal_case(p)).collect()
    }
}

fn type_name_for_path(op: &GraphqlOperation, path: &[&str]) -> String {
    let mut name = pascal_case(&op.operation_name);
    for part in path {
        name.push_str(&pascal_case(part));
    }
    name
}

fn path_with<'a>(path: &[&'a str], item: &'a str) -> Vec<&'a str> {
    let mut next = path.to_vec();
    next.push(item);
    next
}

fn raw_string_literal(value: &str) -> String {
    for hashes in 0..8 {
        let marker = format!("\"{}", "#".repeat(hashes));
        if !value.contains(&marker) {
            let marks = "#".repeat(hashes);
            return format!("r{marks}\"{value}\"{marks}");
        }
    }
    format!("{value:?}")
}

struct FieldIdent {
    name: String,
    needs_rename: bool,
}

fn rust_field_ident(name: &str) -> FieldIdent {
    let snake = to_snake(name);
    let valid = is_valid_rust_ident(&snake);
    if is_rust_keyword(&snake) {
        return FieldIdent {
            name: format!("r#{snake}"),
            needs_rename: true,
        };
    }
    if valid {
        FieldIdent {
            name: snake,
            needs_rename: false,
        }
    } else {
        FieldIdent {
            name: format!("field_{}", sanitize_ident(&snake)),
            needs_rename: true,
        }
    }
}

fn enum_variant_name(name: &str) -> String {
    let variant = if name.contains('_') || name.chars().all(|c| !c.is_ascii_lowercase()) {
        name.split(|c: char| !c.is_ascii_alphanumeric())
            .filter(|part| !part.is_empty())
            .map(|part| {
                let lower = part.to_ascii_lowercase();
                pascal_case(&lower)
            })
            .collect()
    } else {
        pascal_case(name)
    };
    if variant.is_empty() {
        "Unknown".to_string()
    } else if variant.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("Variant{variant}")
    } else {
        variant
    }
}

fn pascal_case(s: &str) -> String {
    let mut out = String::new();
    let mut upper_next = true;
    for c in s.chars() {
        if c.is_ascii_alphanumeric() {
            if upper_next {
                out.push(c.to_ascii_uppercase());
                upper_next = false;
            } else {
                out.push(c);
            }
        } else {
            upper_next = true;
        }
    }
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("Type{out}")
    } else {
        out
    }
}

fn to_snake(s: &str) -> String {
    let mut result = String::new();
    let mut prev_is_lower_or_digit = false;
    for c in s.chars() {
        if c.is_ascii_alphanumeric() {
            if c.is_ascii_uppercase() && prev_is_lower_or_digit {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
            prev_is_lower_or_digit = c.is_ascii_lowercase() || c.is_ascii_digit();
        } else if !result.ends_with('_') {
            result.push('_');
            prev_is_lower_or_digit = false;
        }
    }
    result.trim_matches('_').to_string()
}

fn sanitize_ident(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() || out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert_str(0, "value_");
    }
    out
}

fn is_valid_rust_ident(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c == '_' || c.is_ascii_alphabetic() => {}
        _ => return false,
    }
    chars.all(|c| c == '_' || c.is_ascii_alphanumeric())
}

fn is_rust_keyword(s: &str) -> bool {
    matches!(
        s,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_snake() {
        assert_eq!(to_snake("themeCreate"), "theme_create");
        assert_eq!(to_snake("themeId"), "theme_id");
        assert_eq!(to_snake("checksumMd5"), "checksum_md5");
        assert_eq!(to_snake("id"), "id");
    }

    #[test]
    fn test_keyword_field_ident() {
        let ident = rust_field_ident("type");
        assert_eq!(ident.name, "r#type");
        assert!(ident.needs_rename);
    }

    #[test]
    fn test_pascal_case() {
        assert_eq!(pascal_case("themeCreate"), "ThemeCreate");
        assert_eq!(pascal_case("get_theme"), "GetTheme");
        assert_eq!(
            pascal_case("OnlineStoreThemeFileBodyText"),
            "OnlineStoreThemeFileBodyText"
        );
    }

    #[test]
    fn test_resolve_indexed() {
        let base = vec!["Types".to_string(), "Scalars".to_string()];
        let keys = vec!["String".to_string(), "input".to_string()];
        assert_eq!(resolve_indexed(&base, &keys), "String");

        let keys2 = vec!["Boolean".to_string(), "input".to_string()];
        assert_eq!(resolve_indexed(&base, &keys2), "bool");

        let keys3 = vec!["JSON".to_string(), "input".to_string()];
        assert_eq!(resolve_indexed(&base, &keys3), "serde_json::Value");
    }
}
