use crate::types::*;
use std::collections::HashSet;

/// Options for code generation.
#[derive(Default)]
pub struct GenOptions {
    pub module_name: String,
}

/// Unwrap `Exact<T>` / `Types.Exact<T>` wrappers to get the inner type.
fn unwrap_variables(typ: &TsType) -> Option<&TsType> {
    match typ {
        TsType::Wrapped(w) if w.wrapper == "Exact" || w.wrapper == "Types.Exact" => Some(&w.inner),
        _ => None,
    }
}

/// Generate Rust code for a single GraphQL operation.
pub fn generate_rust(output: &RustOutput, _opts: &GenOptions) -> String {
    let mut code = String::new();
    let mut seen = HashSet::new();

    code.push_str("// Auto-generated by graphql-codegen. Do not edit.\n");
    code.push_str("#![allow(clippy::all)]\n\n");
    code.push_str("use serde::{Deserialize, Serialize};\n\n");

    for st in &output.shared_types {
        generate_shared_type(&mut code, st, &mut seen);
    }

    let constant_name = &output.query_constant_name;
    let raw_query = &output.operation.raw_query;
    code.push_str(&format!(
        "pub const {}: &str = r#\"{}\n\"#;\n\n",
        constant_name, raw_query
    ));

    // Unwrap Types.Exact / Exact to get the inner object for variables
    let var_inner = output.variables_struct.as_ref().and_then(unwrap_variables);
    let var_fields = match var_inner {
        Some(TsType::Object(fields)) => Some(fields),
        _ => output.variables_struct.as_ref().and_then(|v| match v {
            TsType::Object(fields) => Some(fields),
            _ => None,
        }),
    };

    if let Some(fields) = var_fields {
        if !fields.is_empty() {
            code.push_str(&format!(
                "#[derive(Serialize)]\n#[serde(rename_all = \"camelCase\")]\npub struct {}Variables {{\n",
                capitalize(&output.operation.operation_name)
            ));
            for field in fields {
                generate_field_code(&mut code, field, true);
            }
            code.push_str("}\n\n");
        }
    }

    generate_response_structs(
        &mut code,
        &output.response_struct,
        &output.operation,
        &mut seen,
    );

    code
}

fn generate_shared_type(code: &mut String, st: &SharedType, seen: &mut HashSet<String>) {
    if !seen.insert(st.name.clone()) {
        return;
    }
    match &st.kind {
        SharedTypeKind::Enum { variants } => {
            code.push_str(&format!("#[derive(Debug, Clone, Serialize, Deserialize)]\n#[serde(rename_all = \"SCREAMING_SNAKE_CASE\")]\npub enum {} {{\n", st.name));
            for variant in variants {
                let name = ts_enum_to_rust(variant);
                code.push_str(&format!("  {},\n", name));
            }
            code.push_str("}\n\n");
        }
        SharedTypeKind::InputStruct { fields } => {
            code.push_str(&format!(
                "#[derive(Debug, Clone, Serialize)]\n#[serde(rename_all = \"camelCase\")]\npub struct {} {{\n",
                st.name
            ));
            for field in fields {
                generate_field_code(code, field, true);
            }
            code.push_str("}\n\n");
        }
    }
}

fn generate_response_structs(
    code: &mut String,
    typ: &TsType,
    op: &GraphqlOperation,
    seen: &mut HashSet<String>,
) {
    match typ {
        TsType::Object(fields) => {
            let struct_name = format!("{}Response", capitalize(&op.operation_name));
            if !seen.insert(struct_name.clone()) {
                return;
            }
            code.push_str(&format!(
                "#[derive(Deserialize)]\n#[serde(rename_all = \"camelCase\")]\npub struct {} {{\n",
                struct_name
            ));
            for field in fields {
                generate_field_code(code, field, false);
                let cleaned = strip_nullable_wrapper(&field.field_type);
                match &cleaned {
                    TsType::Object(_) => {
                        let nested_name = field_struct_name(&field.name, op);
                        if seen.insert(nested_name.clone()) {
                            generate_nested_struct(code, &cleaned, &nested_name, op, seen);
                        }
                    }
                    TsType::Array(elem) => {
                        let cleaned_elem = strip_nullable_wrapper(elem.as_ref());
                        if let TsType::Object(_) = &cleaned_elem {
                            let nested_name = field_struct_name(&field.name, op);
                            if seen.insert(nested_name.clone()) {
                                generate_nested_struct(code, &cleaned_elem, &nested_name, op, seen);
                            }
                        }
                    }
                    TsType::DiscriminatedUnion { variants, .. } => {
                        for variant in variants {
                            let variant_struct_name =
                                format!("{}{}", capitalize(&op.operation_name), variant.type_name);
                            if seen.insert(variant_struct_name.clone()) {
                                let obj = TsType::Object(variant.fields.clone());
                                generate_nested_struct(code, &obj, &variant_struct_name, op, seen);
                            }
                        }
                    }
                    _ => {}
                }
            }
            code.push_str("}\n\n");
        }
        TsType::DiscriminatedUnion { variants, .. } => {
            let enum_name = format!("{}Body", capitalize(&op.operation_name));
            if !seen.insert(enum_name.clone()) {
                return;
            }
            code.push_str(&format!(
                "#[derive(Deserialize)]\n#[serde(tag = \"__typename\")]\npub enum {} {{\n",
                enum_name
            ));
            for variant in variants {
                let variant_name = ts_enum_to_rust(&variant.type_name);
                let variant_struct =
                    format!("{}{}", capitalize(&op.operation_name), variant.type_name);
                code.push_str(&format!(
                    "  #[serde(rename = \"{}\")]\n  {}({}),\n",
                    variant.type_name, variant_name, variant_struct
                ));
                let obj = TsType::Object(variant.fields.clone());
                generate_nested_struct(code, &obj, &variant_struct, op, seen);
            }
            code.push_str("}\n\n");
        }
        _ => {}
    }
}

fn generate_nested_struct(
    code: &mut String,
    typ: &TsType,
    struct_name: &str,
    _op: &GraphqlOperation,
    _seen: &mut HashSet<String>,
) {
    if let TsType::Object(fields) = typ {
        code.push_str(&format!(
            "#[derive(Deserialize)]\n#[serde(rename_all = \"camelCase\")]\npub struct {} {{\n",
            struct_name
        ));
        for field in fields {
            generate_field_code(code, field, false);
        }
        code.push_str("}\n\n");
    }
}

fn generate_field_code(code: &mut String, field: &TsField, is_variable: bool) {
    let optional = field.optional;
    let rust_type = ts_type_to_rust(&field.field_type, is_variable);

    if optional {
        code.push_str(&format!(
            "  #[serde(skip_serializing_if = \"Option::is_none\")]\n  pub {}: Option<{}>,\n",
            to_snake(&field.name),
            rust_type
        ));
    } else {
        code.push_str(&format!(
            "  pub {}: {},\n",
            to_snake(&field.name),
            rust_type
        ));
    }
}

fn ts_type_to_rust(typ: &TsType, _is_variable: bool) -> String {
    match typ {
        TsType::Primitive(p) => p.to_string(),
        TsType::Array(elem) => format!("Vec<{}>", ts_type_to_rust(elem, _is_variable)),
        TsType::Nullable(inner) => format!("Option<{}>", ts_type_to_rust(inner, _is_variable)),
        TsType::StringUnion(_) => "String".to_string(),
        TsType::Reference(TsReference::Named(parts)) => resolve_reference(parts),
        TsType::Reference(TsReference::Indexed { base, keys }) => resolve_indexed(base, keys),
        TsType::Wrapped(w) => match w.wrapper.as_str() {
            "Maybe" | "InputMaybe" => {
                format!("Option<{}>", ts_type_to_rust(&w.inner, _is_variable))
            }
            "Exact" | "Pick" | "Partial" => ts_type_to_rust(&w.inner, _is_variable),
            _ => ts_type_to_rust(&w.inner, _is_variable),
        },
        TsType::Object(_) | TsType::DiscriminatedUnion { .. } => "serde_json::Value".to_string(),
    }
}

/// Strip outer Nullable/Maybe/InputMaybe wrappers to get at the inner type.
fn strip_nullable_wrapper(typ: &TsType) -> TsType {
    match typ {
        TsType::Nullable(inner) => strip_nullable_wrapper(inner),
        TsType::Wrapped(w) if w.wrapper == "Maybe" || w.wrapper == "InputMaybe" => {
            strip_nullable_wrapper(&w.inner)
        }
        _ => typ.clone(),
    }
}

fn resolve_reference(parts: &[String]) -> String {
    // Strip 'Types.' prefix
    if parts.len() >= 2 && parts[0] == "Types" {
        parts[1..].join("")
    } else if parts.len() == 1 {
        parts[0].clone()
    } else {
        parts.join("")
    }
}

fn resolve_indexed(base: &[String], keys: &[String]) -> String {
    // Types.Scalars['String']['input'] → String
    // Types.Scalars['URL']['input'] → String
    // Types.Scalars['ID']['input'] → String
    // Types.Scalars['Boolean']['input'] → bool
    // Types.Scalars['Int']['input'] → i64
    // Types.Scalars['Float']['input'] → f64
    // Types.Scalars['JSON']['input'] → serde_json::Value
    if base.len() >= 2 && base[0] == "Types" && base[1] == "Scalars" && keys.len() >= 2 {
        let scalar = &keys[0];
        let _dir = &keys[1]; // "input" or "output"
        match scalar.as_str() {
            "String" | "ID" | "URL" => "String".to_string(),
            "Boolean" => "bool".to_string(),
            "Int" => "i64".to_string(),
            "Float" => "f64".to_string(),
            "JSON" => "serde_json::Value".to_string(),
            _ => "serde_json::Value".to_string(),
        }
    } else {
        base.join("")
    }
}

/// Convert TS_SCREAMING_CASE enum value to Rust CamelCase.
fn ts_enum_to_rust(s: &str) -> String {
    s.split('_')
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                Some(c) => {
                    c.to_uppercase().collect::<String>() + chars.as_str().to_lowercase().as_str()
                }
                None => String::new(),
            }
        })
        .collect()
}

fn to_snake(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            result.push('_');
        }
        result.push(c.to_ascii_lowercase());
    }
    result
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

/// Generate a struct name for a field (from its camelCase name).
fn field_struct_name(name: &str, op: &GraphqlOperation) -> String {
    format!("{}{}", capitalize(&op.operation_name), capitalize(name))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_snake() {
        assert_eq!(to_snake("themeCreate"), "theme_create");
        assert_eq!(to_snake("themeId"), "theme_id");
        assert_eq!(to_snake("id"), "id");
    }

    #[test]
    fn test_ts_enum_to_rust() {
        assert_eq!(ts_enum_to_rust("DEVELOPMENT"), "Development");
        assert_eq!(ts_enum_to_rust("ACCESS_DENIED"), "AccessDenied");
        assert_eq!(ts_enum_to_rust("MAIN"), "Main");
    }

    #[test]
    fn test_capitalize() {
        assert_eq!(capitalize("themeCreate"), "ThemeCreate");
        assert_eq!(capitalize("getTheme"), "GetTheme");
    }

    #[test]
    fn test_resolve_indexed() {
        let base = vec!["Types".to_string(), "Scalars".to_string()];
        let keys = vec!["String".to_string(), "input".to_string()];
        assert_eq!(resolve_indexed(&base, &keys), "String");

        let keys2 = vec!["Boolean".to_string(), "input".to_string()];
        assert_eq!(resolve_indexed(&base, &keys2), "bool");

        let keys3 = vec!["JSON".to_string(), "input".to_string()];
        assert_eq!(resolve_indexed(&base, &keys3), "serde_json::Value");
    }
}
